#SIMPLETIMER BY THEBJOREDCRAFT
timer:
  paused: "<i><gray><b>Timer Paused"
  prefix: "<gradient:green:dark_green>"
  suffix:
    days: " Days - "
    hours: " Hours - "
    minutes: " Minutes - "
    seconds: " Seconds"

broadcast:
  start: "Der Timer wurde <b>gestartet!"
  pause: "Der Timer wurde <b>pausiert!"
  resume: "Der Timer wurde <b>fortgesetzt!"
  stop: "Der Timer wurde <b>gestoppt!"
  counter: "Der Timer zählt nun <b>Plus!"
  countdown: "Der Timer zählt nun <b>Minus!"
  reset: "Der Timer wurde <b>resettet!"